### ISSUE TITLE
Question of token vocabulary 

### ISSUE THREAD

**Issue by maojinyang** [feizc/ML-LLaMA#4]
请问针对多语言的词表支持具体做了哪些优化？为什么下图的样例中会生成原始词表中不存在的中文词汇？恳请不吝赐教。
![case1](https://user-images.githubusercontent.com/95010088/228154112-fe7a684e-b2f5-4fad-84c4-8d947388b76c.png)

**Comment by feizc** [comment]
在第一点中有提到，llama天然支持中文，可以使用tokenizer进行编码测试。
